server.port=8080
server.servlet.context-path=/spotitube
spring.application.name=SpotitubeWithSpring
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost/spotitube?user=spotitube&password=1234&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true